### PR TITLE
Use connect with multiple handles

### PR DESCRIPTION
**Pull request by xnakos**
Michael and @leongersen, hi from here too!

Maybe you could look at this. This:

```
    var slider = document.getElementById('slider');
    noUiSlider.create(slider, {
        start: [5, 15, 25, 35],
        step: 1,
        connect: ["#F87217", false, "#8A0707", true, "#F87217"],
        range: {
            min: [0],
            max: [40]
        }
    });
```

results in this:

multiple-handle-connect

P.S. I will create a pull request for the other thingie too. You can do as you please, whenever you please, if you please at all!

### CODE REVIEW

**Comment by michaeltandy** [comment]
There are some unit tests in slider_update.js - do they need to be updated for this change?

**Comment by xnakos** [comment]
To be honest, I have no experience with unit testing in JS. I think that I ran some unit tests accidentally at some point, though! :stuck_out_tongue: If you could tell me one or two things to get me started, I could look into it tomorrow, because it is getting really late here. I am sending a final pull request, if you do not mind, that implements handle stacking using z-index.

After that, I guess I will not be bugging you any more, unless you want me to. :stuck_out_tongue:

**Comment by michaeltandy** [comment]
I'm not much of an expert myself :)

If you already have grunt working, you just need to go into the tests folder and open range.html and slider.html - if they say "188 assertions of 188 passed, 0 failed." and "18 assertions of 18 passed, 0 failed." respectively, your tests are passing.

Then what I did was basically look at the existing tests and go from there. I'm not sure there's all that much testing you can do for this other than making sure the right number of connection divs are present?

**Comment by leongersen** [comment]
Adding colors directly in the JS breaks the separation of concerns between design and functionality (CSS/JS). I think a better option would be to add classes `.noUi-connect-#n` to each connect so they can be separately styled. Secondly, should we standardarize (I haven't reviewed enough to see if you already did this) the connections to separate divs, and remove the current implementation in the `noUi-origin`s?

**Comment by xnakos** [comment]
@michaeltandy The current tests are passing for this pull request / branch. Maybe I could write a test that checks the occurrences of `connect` and `background` classes and see that they match the `true`, `false` occurrences in the connect option and push it here. Is that OK?

@leongersen You are right about separating the colors. Ugly API is ugly, mixing boolean with color strings. How and where would you parse and apply something like `.noUi-connect-#7f4e2a`, though? Or maybe I misunderstood. Do you mean that classes provided by an external CSS could be used in the connect array? Something like `[true, false, "noUi-connect-#one", true, "myBlackBackground"]`. And if something is not false and !== true, then addClass(it) in the code? Ugly API is still ugly, right? Or have a separate option for connect colors? Something like:

```
connectStyle: ['default', 'myBlackBackground'],
```

and apply it one-by-one to connects (skipping no-connects), continuing from the beginning if the number of connects is bigger than the number of connect styles.

```
connectStyle: ['myBlackBackground'],
```

would, thus, be perfect for styling a Black Metal timeline with many connects. Anyway, what is your opinion? Maybe this could be merged (since the color option could be hidden for now, advertising the pure boolean array only) and think it over.

**Comment by michaeltandy** [comment]
@xnakos I think what leongersen means is an interface like this:

```
<style>
#noUi-connect-0 {
    background: #F87217;
}
#noUi-connect-2 {
    background: #8A0707;
}
#noUi-connect-4 {
    background: #F87217;
}
</style>
<script>
    var slider = document.getElementById('slider');
    noUiSlider.create(slider, {
        start: [5, 15, 25, 35],
        step: 1,
        connect: [true, false, true, true, true],
        range: {
            min: [0],
            max: [40]
        }
    });
</script>
```

This would be closer to the ["separation of content and presentation"](https://en.wikipedia.org/wiki/Separation_of_presentation_and_content) usually seen in HTML. Of course, when you're making a JS UI library you can't make such a clean separation as you could with, say, a blog post :)

A unit test that counts the connect and background divs (or the number of divs styled `.noUi-connect-#n` as that's what leongersen wants) would be OK with me.

**Pull request closed without merging**
